1)
Hash of the package https://pypi.python.org/packages/2.7/b/boto/boto-2.34.0-py2.py3-none-any.whl#md5=993cd85edce146375af0531d483bf2c7 (from https://pypi.python.org/simple/boto/) (49f7445cff7572f359da8a66be252b12) doesn't match the expected hash 993cd85edce146375af0531d483bf2c7!
  Bad md5 hash for package https://pypi.python.org/packages/2.7/b/boto/boto-2.34.0-py2.py3-none-any.whl#md5=993cd85edce146375af0531d483bf2c7 (from https://pypi.python.org/simple/boto/)
重新执行一遍又好了

2)
+ /sbin/grub2-install '--modules=biosdisk part_msdos' /dev/loop3
Installing for i386-pc platform.
/sbin/grub2-install: warning: File system `ext2' doesn't support embedding.
/sbin/grub2-install: warning: Embedding is not possible.  GRUB can only be installed in this setup by using blocklists.  However, blocklists are UNRELIABLE and their use is discouraged..
/sbin/grub2-install: error: will not proceed with blocklists.
/dev/loop3: [64773]:534347 (/tmp/image.tttQ9BK1/image.raw)
umount: /tmp/image.VwAa2stF: not mounted
umount: /tmp/image.tttQ9BK1: not mounted

3)
http://mirrors.hust.edu.cn/centos/7.0.1406/updates/x86_64/Packages/linux-firmware-20140804-0.1.git6bce2b0.el7_0.noarch.rpm: [Errno 12] Timeout on http://mirrors.hust.edu.cn/centos/7.0.1406/updates/x86_64/Packages/linux-firmware-20140804-0.1.git6bce2b0.el7_0.noarch.rpm: (28, 'Operation too slow. Less than 1000 bytes/sec transferred the last 30 seconds')
Trying other mirror.
Traceback (most recent call last):.1 57% [==============-           ]  0.0 B/s |  37 MB  --:--:-- ETA 
  File "/usr/libexec/urlgrabber-ext-down", line 75, in <module>
    main()
  File "/usr/libexec/urlgrabber-ext-down", line 61, in main
    fo = PyCurlFileObject(opts.url, opts.filename, opts)
  File "/usr/lib/python2.7/site-packages/urlgrabber/grabber.py", line 1258, in __init__
    self._do_open()
  File "/usr/lib/python2.7/site-packages/urlgrabber/grabber.py", line 1589, in _do_open
    self._do_grab()
  File "/usr/lib/python2.7/site-packages/urlgrabber/grabber.py", line 1723, in _do_grab
    self._do_perform()
  File "/usr/lib/python2.7/site-packages/urlgrabber/grabber.py", line 1517, in _do_perform
    raise KeyboardInterrupt
KeyboardInterrupt
  
  
